In [ ]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from requests import get
from time import *
from random import randint
from IPython.core.display import clear_output
from tensorflow.python.keras import models
from tensorflow.python.keras import layers
from sklearn.model_selection import train_test_split

In [ ]:
nfl = pd.read_csv('/content/drive/MyDrive/AmericanFootball98.csv')
nfl

team_code  wins  ...  opp avg yards per drive  opp avg points per drive
0     nwe2019    12  ...                     22.8                      1.00
1     buf2019    10  ...                     26.2                      1.29
2     nyj2019     7  ...                     26.7                      1.81
3     mia2019     5  ...                     34.3                      2.53
4     rav2019    14  ...                     28.8                      1.65
..        ...   ...  ...                      ...                       ...
664   ram1999    13  ...                     23.7                      1.12
665   car1999     8  ...                     29.8                      1.79
666   atl1999     5  ...                     28.1                      1.86
667   sfo1999     4  ...                     30.5                      2.20
668   nor1999     3  ...                     26.8                      1.97

[669 rows x 63 columns]

In [ ]:
x = nfl.loc[2]
x.team_code

'nyj2019'

In [ ]:
def splitString(x):
  team = x[:3]
  year = x[3:]
  return (team, year)

In [ ]:
spl = np.vectorize(splitString)(nfl['team_code'])
spl

(array(['nwe', 'buf', 'nyj', 'mia', 'rav', 'pit', 'cle', 'cin', 'htx',
        'oti', 'clt', 'jax', 'kan', 'den', 'rai', 'sdg', 'phi', 'dal',
        'nyg', 'was', 'gnb', 'min', 'chi', 'det', 'nor', 'atl', 'tam',
        'car', 'sfo', 'sea', 'ram', 'crd', 'nwe', 'mia', 'buf', 'nyj',
        'rav', 'pit', 'cle', 'cin', 'htx', 'clt', 'oti', 'jax', 'kan',
        'sdg', 'den', 'rai', 'dal', 'phi', 'was', 'nyg', 'chi', 'min',
        'gnb', 'det', 'nor', 'atl', 'car', 'tam', 'ram', 'sea', 'sfo',
        'crd', 'nwe', 'buf', 'mia', 'nyj', 'pit', 'rav', 'cin', 'cle',
        'jax', 'oti', 'clt', 'htx', 'kan', 'sdg', 'rai', 'den', 'phi',
        'dal', 'was', 'nyg', 'min', 'det', 'gnb', 'chi', 'nor', 'car',
        'atl', 'tam', 'ram', 'sea', 'crd', 'sfo', 'nwe', 'mia', 'buf',
        'nyj', 'pit', 'rav', 'cin', 'cle', 'htx', 'oti', 'clt', 'jax',
        'kan', 'rai', 'den', 'sdg', 'dal', 'nyg', 'was', 'phi', 'gnb',
        'det', 'min', 'chi', 'atl', 'tam', 'nor', 'car', 'sea', 'crd',
      

In [ ]:
nfl['Team'] = spl[0]
nfl['Year'] = spl[1]
nfl = nfl.drop(['team_code'], axis=1)
nfl

wins  losses   PF  ...  opp avg points per drive  Team  Year
0      12       4  420  ...                      1.00   nwe  2019
1      10       6  314  ...                      1.29   buf  2019
2       7       9  276  ...                      1.81   nyj  2019
3       5      11  306  ...                      2.53   mia  2019
4      14       2  531  ...                      1.65   rav  2019
..    ...     ...  ...  ...                       ...   ...   ...
664    13       3  526  ...                      1.12   ram  1999
665     8       8  421  ...                      1.79   car  1999
666     5      11  285  ...                      1.86   atl  1999
667     4      12  295  ...                      2.20   sfo  1999
668     3      13  260  ...                      1.97   nor  1999

[669 rows x 64 columns]

In [ ]:
map = [('nwe', 'Patriots'), ('buf', 'Bills'), ('nyj', 'Jets'), ('mia', 'Dolphins'), ('rav', 'Ravens'), ('pit', 'Steelers'),
       ('cle', 'Browns'), ('cin', 'Bengals'), ('htx', 'Texans'), ('oti', 'Titans'), ('clt', 'Colts'), ('jax', 'Jaguars'),
       ('kan', 'Chiefs'), ('den', 'Broncos'), ('rai', 'Raiders'), ('sdg', 'Chargers'), ('phi', 'Eagles'), ('dal', 'Cowboys'),
       ('nyg', 'Giants'), ('was', 'Redskins'), ('gnb', 'Packers'), ('min', 'Vikings'), ('chi', 'Bears'), ('det', 'Lions'),
       ('nor', 'Saints'), ('atl', 'Falcons'), ('tam', 'Buccaneers'), ('car', 'Panthers'), ('sfo', '49ers'), ('sea', 'Seahawks'),
       ('ram', 'Rams'), ('crd', 'Cardinals')]
nfl['Team'] = nfl['Team'].map(dict(map))
nfl

wins  losses   PF  ...  opp avg points per drive      Team  Year
0      12       4  420  ...                      1.00  Patriots  2019
1      10       6  314  ...                      1.29     Bills  2019
2       7       9  276  ...                      1.81      Jets  2019
3       5      11  306  ...                      2.53  Dolphins  2019
4      14       2  531  ...                      1.65    Ravens  2019
..    ...     ...  ...  ...                       ...       ...   ...
664    13       3  526  ...                      1.12      Rams  1999
665     8       8  421  ...                      1.79  Panthers  1999
666     5      11  285  ...                      1.86   Falcons  1999
667     4      12  295  ...                      2.20     49ers  1999
668     3      13  260  ...                      1.97    Saints  1999

[669 rows x 64 columns]

# Create multi index for team and year

In [ ]:
index = pd.MultiIndex.from_arrays([nfl['Team'].values, nfl['Year'].values])
index

MultiIndex([(  'Patriots', '2019'),
            (     'Bills', '2019'),
            (      'Jets', '2019'),
            (  'Dolphins', '2019'),
            (    'Ravens', '2019'),
            (  'Steelers', '2019'),
            (    'Browns', '2019'),
            (   'Bengals', '2019'),
            (    'Texans', '2019'),
            (    'Titans', '2019'),
            ...
            ('Buccaneers', '1999'),
            (   'Vikings', '1999'),
            (     'Lions', '1999'),
            (   'Packers', '1999'),
            (     'Bears', '1999'),
            (      'Rams', '1999'),
            (  'Panthers', '1999'),
            (   'Falcons', '1999'),
            (     '49ers', '1999'),
            (    'Saints', '1999')],
           length=669)

In [ ]:
nfl.index = index
nfl.index.names = ['Team', 'Year']
df_nfl = nfl
df_nfl

wins  losses   PF  ...  opp avg points per drive      Team  Year
Team     Year                     ...                                          
Patriots 2019    12       4  420  ...                      1.00  Patriots  2019
Bills    2019    10       6  314  ...                      1.29     Bills  2019
Jets     2019     7       9  276  ...                      1.81      Jets  2019
Dolphins 2019     5      11  306  ...                      2.53  Dolphins  2019
Ravens   2019    14       2  531  ...                      1.65    Ravens  2019
...             ...     ...  ...  ...                       ...       ...   ...
Rams     1999    13       3  526  ...                      1.12      Rams  1999
Panthers 1999     8       8  421  ...                      1.79  Panthers  1999
Falcons  1999     5      11  285  ...                      1.86   Falcons  1999
49ers    1999     4      12  295  ...                      2.20     49ers  1999
Saints   1999     3      13  260  ...                      1.97    Saints  1999

[669 rows x 64 columns]

# Find Stats Most Correlated to # of Wins

In [ ]:
nfl.corr()['wins'].sort_values(ascending=False)[1:]

PF                            0.729011
score percentage              0.676604
avg points per drive          0.672206
net yards per pass att        0.588719
yards                         0.509563
pass td                       0.496598
1st downs                     0.496492
yards/play                    0.494568
rush td                       0.489592
opp turnover percentage       0.487915
avg yards per drive           0.475213
Unnamed: 17                   0.470936
rush 1st downs                0.443812
opp TO                        0.431575
opp int                       0.418878
rush yards                    0.379062
opp pass attempts             0.374563
pass yards                    0.318479
avg plays per drive           0.311842
pass 1st downs                0.299420
plays                         0.263039
opp Fumbles Lost              0.223082
rush yards per att            0.130259
completions                   0.124187
opp completions               0.104197
pen 1st downs            

In [ ]:
years = np.arange(1999,  2020)
years = [str(x) for x in years]
years

['1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019']

# Web Scraper to Collect Data for NFL Teams

In [ ]:
requests = 0
test = []
schedule = []
week = []
start_time = time()
for year in years:
  response = get('https://www.pro-football-reference.com/years/' + year + '/games.htm')
  sleep(randint(5, 11))
  requests += 1
  elapsed_time = time() - start_time
  print('Request:{}; Frequency: {} requests/s'.format(requests, requests/elapsed_time))
  clear_output(wait=True)
  if response.status_code != 200:
    warn('Request: {}; Status code: {}'.format(requests, response.status_code))
  html_soup = BeautifulSoup(response.text, 'html.parser')
  nfl = html_soup.find_all('div', class_ = 'table_outer_container')
  test = nfl[0].div.table.tbody
  rows = test.find_all('tr')
  col = []
  result = []
  for row in rows:
    cols = row.find_all('td')
    col.append(cols)
  col[0]
  for x in range(len(col)):
    for y in range(len(col[x])):
      #print(col[x][y].text)
      result.append(col[x][y].text)
    #result.append(year)
  if len(result) == 3484:
    result = np.array(result).reshape((268, 13))
    result = np.delete(result, 256, 0)
  else:
    result = np.reshape(result, (260, 13))
    result = np.delete(result, 248, 0)
  schedule.append(result)
  test = nfl[0].div.table.tbody
  rows = test.find_all('tr')
  col = []
  result = []
  for row in rows:
    cols = row.find_all('th')
    col.append(cols)
  col[0][0].text
  for x in range(len(col)):
    for y in range(len(col[x])):
      #print(col[x][y].text)
      result.append(col[x][y].text)
  result2 = []
  l = ['WildCard', 'Division', 'ConfChamp', 'SuperBowl']
  for x in range(len(result)):
    if result[x].isnumeric() and result[x].isnumeric() <= 57 or (result[x] in l):
      result2.append(result[x])
  week.append(result2)

Request:21; Frequency: 0.11578250163651174 requests/s


In [ ]:
schedule

[array([['Sun', 'September 12', '1:00PM', ..., '3', '504', '2'],
        ['Sun', 'September 12', '1:02PM', ..., '2', '363', '4'],
        ['Sun', 'September 12', '1:02PM', ..., '2', '349', '1'],
        ...,
        ['Sun', 'January 23', '12:42PM', ..., '4', '355', '6'],
        ['Sun', 'January 23', '4:22PM', ..., '3', '203', '2'],
        ['Sun', 'January 30', '6:25PM', ..., '0', '367', '0']],
       dtype='<U20'),
 array([['Sun', 'September 3', '1:00PM', ..., '1', '425', '1'],
        ['Sun', 'September 3', '1:00PM', ..., '2', '280', '1'],
        ['Sun', 'September 3', '1:01PM', ..., '0', '236', '1'],
        ...,
        ['Sun', 'January 14', '12:37PM', ..., '2', '114', '5'],
        ['Sun', 'January 14', '4:05PM', ..., '2', '191', '5'],
        ['Sun', 'January 28', '6:28PM', ..., '0', '152', '5']],
       dtype='<U20'),
 array([['Sun', 'September 9', '12:01PM', ..., '3', '254', '3'],
        ['Sun', 'September 9', '12:02PM', ..., '1', '288', '3'],
        ['Sun', 'September 9', 

In [ ]:
len(schedule[1])

259

In [ ]:
df = pd.DataFrame(schedule[0])
l = []
l.append([1999] * len(schedule[0]))
for x in range(1, len(schedule)):
  num = 1999 + x
  l.append([num] * len(schedule[x]))
  df = pd.concat([df, pd.DataFrame(schedule[x])], ignore_index=True)
  
df.columns = ['Day', 'Date', 'Time', 'Winning Team', 'At?', 'Losing Team','boxscore', 'PtsW', 'PtsL', 'YdsW', 'TOW', 'YdsL', 'TOL']
l = np.concatenate(l).ravel()
len(l)

5583

In [ ]:
week = np.concatenate(week).ravel()
df['Week'] = week
df['Year'] = l
df

Day          Date    Time          Winning Team  ... YdsL TOL       Week  Year
0     Sun  September 12  1:00PM        Dallas Cowboys  ...  504   2          1  1999
1     Sun  September 12  1:02PM  New England Patriots  ...  363   4          1  1999
2     Sun  September 12  1:02PM         Chicago Bears  ...  349   1          1  1999
3     Sun  September 12  1:02PM    New Orleans Saints  ...  246   3          1  1999
4     Sun  September 12  1:02PM        St. Louis Rams  ...  223   2          1  1999
...   ...           ...     ...                   ...  ...  ...  ..        ...   ...
5578  Sun    January 12  3:05PM    Kansas City Chiefs  ...  442   1   Division  2019
5579  Sun    January 12  6:40PM     Green Bay Packers  ...  375   0   Division  2019
5580  Sun    January 19  3:05PM    Kansas City Chiefs  ...  295   0  ConfChamp  2019
5581  Sun    January 19  6:40PM   San Francisco 49ers  ...  358   3  ConfChamp  2019
5582  Sun    February 2  6:30PM    Kansas City Chiefs  ...  351   2  SuperBowl  2019

[5583 rows x 15 columns]

# Function to Find Data for Each Team per Year

In [ ]:
def getSeasonData(team, year):
  team_data = df_nfl.loc[team, year]
  ypp = team_data['yards/play']
  pypa = team_data['net yards per pass att']
  rypa = team_data['rush yards per att']
  sp = team_data['score percentage']
  top = team_data['turnover percentage']
  appd = team_data['avg points per drive']
  oypp = team_data['opp yards/play']
  opypa = team_data['opp net yards per pass att']
  orypa = team_data['opp rush yards per att']
  osp = team_data['opp score percentage']
  otop = team_data['opp turnover percentage']
  oappd = team_data['opp avg points per drive']
  return [ypp, pypa, rypa, sp, top, appd, oypp, opypa, orypa, osp, otop, oappd]

In [ ]:
def compareTeams(team_1, team_2, year):
  t1 = np.array(getSeasonData(team_1, year))
  t2 = np.array(getSeasonData(team_2, year))
  diff = t1 - t2
  return diff

In [ ]:
def createDict(year):
  d = {}
  df2 = df_nfl[df_nfl['Year'] == year]
  for x in range(len(df2)):
    d[df2.iloc[x]['Team']] = getSeasonData(df2.iloc[x]['Team'], year)
  return d


In [ ]:
def getHome(at):
  if at == '@':
    return -1
  elif at == ' ':
    return 1
  else:
    return 0

In [ ]:
def createSets(years):
  totalGames = len(df)
  xTrain = np.zeros((totalGames, 13))
  yTrain = np.zeros((totalGames))
  i = 0
  for year in years:
    season_dict = createDict(str(year))
    #print(season_dict)
    season = df[df['Year'] == year]
    xTrainSeason = np.zeros((df[df['Year'] == year]['Year'].count(), 13))
    yTrainSeason = np.zeros((df[df['Year'] == year]['Year'].count()))
    count = 0
    #print(xTrainSeason)
    
    for x in range(len(season)):
      wTeam = season.iloc[x]['Winning Team']
      wStats = wTeam.split()
      mascot = wStats[len(wStats)-1]
      wStats = season_dict[mascot]
      lTeam = season.iloc[x]['Losing Team']
      lStats = lTeam.split()
      mascot2 = lStats[len(lStats)-1]
      lStats = season_dict[mascot2]
      home = getHome(season.iloc[x]['At?'])
      diff = compareTeams(mascot, mascot2, str(year))
      if count % 2 == 0:
        diff = np.append(diff, home)
        xTrainSeason[count] = diff
        yTrainSeason[count] = 1
      else:
        diff = np.append(diff, -home)
        xTrainSeason[count] = -diff
        yTrainSeason[count] = 0
      count += 1
    #print(yTrainSeason)
    xTrain[i:(df[df['Year'] == year]['Year'].count()) + i] = xTrainSeason
    yTrain[i:(df[df['Year'] == year]['Year'].count()) + i] = yTrainSeason
    i += df[df['Year'] == year]['Year'].count()
  return xTrain, yTrain
  

In [ ]:
X_train, Y_train = createSets(np.arange(1999, 2020))

In [ ]:
X_train.shape

(5583, 13)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(X_train, Y_train, test_size=0.2)
x_train

array([[-0.4 , -0.7 ,  0.4 , ..., 10.7 , -0.7 ,  0.  ],
       [-0.2 , -0.4 ,  0.  , ...,  6.2 ,  0.03, -1.  ],
       [-0.4 ,  0.  , -0.6 , ...,  6.9 , -0.54,  0.  ],
       ...,
       [-0.5 , -0.8 , -0.2 , ..., -2.3 , -0.61,  0.  ],
       [ 0.5 ,  1.1 , -0.1 , ..., -0.7 ,  0.24, -1.  ],
       [-0.5 , -1.  , -0.5 , ..., -1.7 ,  0.37, -0.  ]])

# Recurrent Neural Network to Predict Which Team Will Win

In [ ]:
model = models.Sequential()
model.add(layers.Dense(8, activation='relu', input_shape=(13,)))
model.add(layers.Dense(8, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=3)

Epoch 1/3
140/140 [==============================] - 0s 1ms/step - loss: 0.6584 - accuracy: 0.6111
Epoch 2/3
140/140 [==============================] - 0s 1ms/step - loss: 0.6021 - accuracy: 0.6776
Epoch 3/3
140/140 [==============================] - 0s 984us/step - loss: 0.5911 - accuracy: 0.6892


In [ ]:
results = model.evaluate(x_test, y_test)

35/35 [==============================] - 0s 1ms/step - loss: 0.5839 - accuracy: 0.7117


# 71% Accurate Which Team Will Win

In [ ]:
bills = np.array([6.2, 7.1, 4.1, 47.8, 13.0, 2.62, 5.7, 6.5, 4.7, 45.5, 15.2, 2.51, 0])
niners = np.array([5.6, 6.7, 4.1, 38.3, 14.2, 2.15, 5.2, 6.2, 4.0, 38.5, 12.3, 1.98, 0])
washington = np.array([5.0, 5.7, 4.1, 35.0, 13.0, 1.93, 5.0, 5.6, 4.3, 37.1, 10.5, 1.92, -1])
steelers = np.array([5.2, 6.1, 3.8, 42.1, 7.1, 2.37, 4.9, 5.3, 4.4, 26.0, 17.3, 1.47, 1])
cowboys = np.array([5.3, 6.0, 4.2, 37.9, 18.5, 1.98, 5.8, 6.7, 4.9, 46.8, 8.1, 2.69, -1])
ravens = np.array([5.4, 5.9, 4.9, 39.2, 11.7, 2.11, 5.2, 5.6, 4.5, 30.0, 13.3, 1.70, 1])
broncos = np.array([5.1, 5.8, 4.3, 31.6, 19.5, 1.58, 5.1, 5.7, 4.5, 41.5, 8.5, 2.14, -1])
chiefs = np.array([6.5, 7.7, 4.4, 52.3, 7.3, 3.04, 5.7, 6.4, 4.7, 36.8, 14.9, 2.05, 1])

In [ ]:
#Week 14 stats
rams = np.array([5.8, 7.0, 4.2, 35.2, 12.7, 2.04, 4.6, 5.1, 3.9, 29.2, 14.6, 1.58, 1])
patriots = np.array([5.4, 6.4, 4.6, 39.8, 14.4, 2.11, 5.8, 7.0, 4.3, 40.5, 15.5, 2.15, -1])
redskins = np.array([5.0, 5.7, 4.0, 35.3, 11.8, 1.93, 5.0, 5.7, 4.1, 37.1, 10.5, 1.92, 0])
niners = np.array([5.7, 6.8, 4.1, 38.8, 14.7, 2.15, 5.3, 6.5, 3.9, 38.5, 12.3, 1.98, 0])
texans = np.array([6.3, 7.7, 3.9, 42.3, 8.9, 2.31, 6.0, 6.9, 4.9, 42.5, 6.3, 2.47, -1])
bears = np.array([4.8, 5.3, 4.0, 33.1, 12.8, 1.74, 5.4, 6.4, 4.0, 38.6, 8.6, 1.96, 1])
bengals = np.array([4.8, 5.3, 3.8, 33.6, 13.4, 1.72, 6.0, 7.0, 4.7, 43.4, 8.8, 2.24, 1])
cowboys = np.array([5.3, 6.0, 4.2, 37.9, 18.5, 1.98, 5.9, 6.6, 5.2, 46.8, 8.1, 2.69, -1])
chiefs = np.array([6.5, 7.7, 4.5, 52.9, 6.7, 2.97, 5.6, 6.3, 4.8, 36.6, 15.4, 2.04, -1])
dolphins = np.array([5.2, 6.5, 3.7, 42.7, 10.7, 2.14, 5.6, 6.3, 4.6, 26.3, 15.8, 1.60, 1])
cardinals = np.array([5.8, 6.4, 5.0, 44.2, 11.6, 2.60, 5.4, 6.0, 4.5, 42.1, 10.3, 2.25, -1])
giants = np.array([5.0, 5.4, 4.5, 35.9, 13.3, 1.70, 5.4, 6.2, 4.0, 39.8, 14.6, 2.07, 1])
vikings = np.array([6.3, 7.6, 4.9, 38.2, 14.7, 2.32, 5.8, 6.8, 4.3, 45.0, 10.9, 2.31, -1])
buccaneers = np.array([5.7, 6.5, 4.2, 44.9, 11.0, 2.49, 5.2, 6.3, 3.3, 34.8, 14.5, 1.94, 1])
broncos = np.array([5.2, 5.7, 4.4, 31.7, 19.7, 1.60, 5.3, 5.9, 4.6, 42.9, 7.9, 2.14, -1])
panthers = np.array([5.8, 6.9, 4.2, 45.2, 11.3, 2.33, 5.7, 6.4, 4.6, 48.7, 13.7, 2.59, 1])
titans = np.array([6.0, 7.2, 4.8, 46.8, 6.3, 2.77, 5.7, 6.8, 4.2, 43.7, 12.7, 2.58, -1])
jaguars = np.array([5.4, 5.8, 4.6, 33.6, 14.8, 1.85, 6.2, 7.7, 4.4, 47.1, 9.4, 2.57, 1])
colts = np.array([5.6, 7.1, 3.7, 42.6, 9.3, 2.24, 5.3, 6.4, 3.8, 34.9, 14.3, 1.97, -1])
raiders = np.array([5.7, 6.9, 4.2, 48.0, 13.6, 2.59, 5.8, 6.7, 4.5, 48.8, 11.4, 2.73, 1])
jets = np.array([4.7, 5.0, 4.4, 26.4, 12.4, 1.35, 5.8, 7.4, 3.8, 46.2, 11.4, 2.51, -1])
seahawks = np.array([6.0, 6.8, 4.7, 44.0, 11.9, 2.60, 5.8, 6.8, 4.0, 43.6, 12.0, 2.42, 1])
packers = np.array([6.3, 7.6, 4.5, 48.0, 6.4, 2.91, 5.6, 6.4, 4.6, 40.2, 10.7, 2.25, -1])
lions = np.array([5.6, 6.6, 3.9, 38.9, 9.9, 2.18, 6.0, 7.3, 4.5, 44.1, 9.4, 2.68, 1])
saints = np.array([5.6, 6.7, 4.4, 45.8, 8.4, 2.60, 4.9, 5.8, 3.3, 35.7, 12.4, 1.88, -1])
eagles = np.array([4.9, 4.8, 5.0, 28.8, 15.8, 1.67, 5.2, 6.0, 4.2, 37.4, 6.8, 2.05, 1])
falcons = np.array([5.4, 6.5, 3.7, 46.3, 8.8, 2.27, 6.2, 7.2, 4.5, 39.8, 12.8, 2.28, -1])
chargers = np.array([5.3, 6.4, 3.8, 34.8, 10.1, 1.94, 5.5, 6.1, 4.6, 44.0, 8.2, 2.43, 1])
steelers = np.array([5.2, 6.1, 3.7, 40.3, 7.2, 2.27, 4.9, 5.3, 4.2, 27.1, 15.7, 1.50, -1])
bills = np.array([6.0, 7.2, 4.0, 48.8, 12.8, 2.68, 5.8, 6.6, 4.7, 45.5, 15.7, 2.25, 1])
ravens = np.array([5.5, 6.0, 5.2, 39.2, 11.7, 2.11, 5.2, 5.6, 4.4, 30.0, 13.3, 1.70, -1])
browns = np.array([5.9, 6.9, 4.9, 41.5, 10.6, 2.35, 5.5, 6.4, 4.1, 42.7, 16.1, 2.48, 1])

In [ ]:
x_test

array([[ 0.  ,  1.4 , -1.4 , ...,  5.1 , -0.45,  0.  ],
       [-0.8 , -1.4 ,  0.2 , ..., -3.9 ,  0.29, -0.  ],
       [-0.6 , -1.2 , -0.1 , ..., -1.5 ,  0.11, -0.  ],
       ...,
       [-0.5 , -1.6 ,  0.5 , ...,  9.9 , -0.11, -1.  ],
       [-1.  , -1.4 , -0.7 , ...,  6.  , -0.16,  0.  ],
       [ 1.  ,  1.1 ,  0.9 , ...,  3.  , -0.  , -1.  ]])

In [ ]:
t = compareTeams('Bengals', 'Ravens', '2019')
t = np.append(t, 0)
t = t.reshape((1, 13))
t

array([[ -1.2 ,  -1.4 ,  -1.6 , -21.8 ,   7.4 ,  -1.43,   0.9 ,   1.7 ,
          0.3 ,   6.9 ,  -5.8 ,   0.47,   0.  ]])

In [ ]:
predictions = np.array(rams-patriots)
predictions = np.append(predictions, redskins-niners)
predictions = np.append(predictions, texans-bears)
predictions = np.append(predictions, bengals-cowboys)
predictions = np.append(predictions, chiefs-dolphins)
predictions = np.append(predictions, cardinals-giants)
predictions = np.append(predictions, vikings-buccaneers)
predictions = np.append(predictions, broncos-panthers)
predictions = np.append(predictions, titans-jaguars)
predictions = np.append(predictions, colts-raiders)
predictions = np.append(predictions, jets-seahawks)
predictions = np.append(predictions, packers-lions)
predictions = np.append(predictions, saints-eagles)
predictions = np.append(predictions, falcons-chargers)
predictions = np.append(predictions, steelers-bills)
predictions = np.append(predictions, ravens-browns)
predictions = predictions.reshape((16, 13))
predictions

array([[ 4.00e-01,  6.00e-01, -4.00e-01, -4.60e+00, -1.70e+00, -7.00e-02,
        -1.20e+00, -1.90e+00, -4.00e-01, -1.13e+01, -9.00e-01, -5.70e-01,
         2.00e+00],
       [-7.00e-01, -1.10e+00, -1.00e-01, -3.50e+00, -2.90e+00, -2.20e-01,
        -3.00e-01, -8.00e-01,  2.00e-01, -1.40e+00, -1.80e+00, -6.00e-02,
         0.00e+00],
       [ 1.50e+00,  2.40e+00, -1.00e-01,  9.20e+00, -3.90e+00,  5.70e-01,
         6.00e-01,  5.00e-01,  9.00e-01,  3.90e+00, -2.30e+00,  5.10e-01,
        -2.00e+00],
       [-5.00e-01, -7.00e-01, -4.00e-01, -4.30e+00, -5.10e+00, -2.60e-01,
         1.00e-01,  4.00e-01, -5.00e-01, -3.40e+00,  7.00e-01, -4.50e-01,
         2.00e+00],
       [ 1.30e+00,  1.20e+00,  8.00e-01,  1.02e+01, -4.00e+00,  8.30e-01,
         0.00e+00,  0.00e+00,  2.00e-01,  1.03e+01, -4.00e-01,  4.40e-01,
        -2.00e+00],
       [ 8.00e-01,  1.00e+00,  5.00e-01,  8.30e+00, -1.70e+00,  9.00e-01,
         0.00e+00, -2.00e-01,  5.00e-01,  2.30e+00, -4.30e+00,  1.80e-01,
        -2.0

In [ ]:
model.predict(predictions)

array([[0.75319076],
       [0.47804004],
       [0.58635414],
       [0.5620557 ],
       [0.53295755],
       [0.53991604],
       [0.18193525],
       [0.17088947],
       [0.81378925],
       [0.7256861 ],
       [0.20715585],
       [0.76545775],
       [0.83165926],
       [0.6937895 ],
       [0.7280185 ],
       [0.70932925]], dtype=float32)

In [ ]:
df[df['Year'] == 2019]

Day         Date    Time         Winning Team  ... YdsL TOL       Week  Year
5316  Thu  September 5  8:20PM    Green Bay Packers  ...  254   1          1  2019
5317  Sun  September 8  1:00PM     Tennessee Titans  ...  346   3          1  2019
5318  Sun  September 8  1:00PM    Minnesota Vikings  ...  345   3          1  2019
5319  Sun  September 8  1:00PM  Philadelphia Eagles  ...  398   0          1  2019
5320  Sun  September 8  1:00PM     Los Angeles Rams  ...  343   3          1  2019
...   ...          ...     ...                  ...  ...  ...  ..        ...   ...
5578  Sun   January 12  3:05PM   Kansas City Chiefs  ...  442   1   Division  2019
5579  Sun   January 12  6:40PM    Green Bay Packers  ...  375   0   Division  2019
5580  Sun   January 19  3:05PM   Kansas City Chiefs  ...  295   0  ConfChamp  2019
5581  Sun   January 19  6:40PM  San Francisco 49ers  ...  358   3  ConfChamp  2019
5582  Sun   February 2  6:30PM   Kansas City Chiefs  ...  351   2  SuperBowl  2019

[267 rows x 15 columns]